spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      # create / create-drop / update / validate
      # ?? ???? ????? validate? none
      ddl-auto: create-drop
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibername.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/board-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    user.name: ${ADMIN_USERNAME}
    user.password: ${ADMIN_PASSWORD}
  logging:
    level:
      #TRACE < DEBUG < INFO < WARN < ERROR
      root: INFO